// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: company_queries.sql

package sqlc

import (
	"context"
)

const createCompany = `-- name: CreateCompany :exec
INSERT INTO company_table (company_name, poc_name, poc_phno, industry, username, password)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCompanyParams struct {
	CompanyName string `json:"company_name"`
	PocName     string `json:"poc_name"`
	PocPhno     string `json:"poc_phno"`
	Industry    string `json:"industry"`
	Username    string `json:"username"`
	Password    string `json:"password"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) error {
	_, err := q.db.Exec(ctx, createCompany,
		arg.CompanyName,
		arg.PocName,
		arg.PocPhno,
		arg.Industry,
		arg.Username,
		arg.Password,
	)
	return err
}