// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AuthenticateCompany(ctx context.Context, arg AuthenticateCompanyParams) (int32, error)
	AuthenticateStudent(ctx context.Context, arg AuthenticateStudentParams) (int32, error)
	CheckIfCompanyExists(ctx context.Context, companyName string) (bool, error)
	CheckIfStudentExists(ctx context.Context, usn string) (bool, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) error
	CreateJob(ctx context.Context, arg CreateJobParams) error
	GetAlreadyAppliedJobs(ctx context.Context, studentID int32) ([]int32, error)
	GetEligibleStudents(ctx context.Context, jobID int32) ([]*GetEligibleStudentsRow, error)
	GetJobOfferActByDate(ctx context.Context, arg GetJobOfferActByDateParams) (pgtype.Timestamp, error)
	GetJobOffers(ctx context.Context, studentID int32) ([]*GetJobOffersRow, error)
	GetJobs(ctx context.Context, arg GetJobsParams) ([]*GetJobsRow, error)
	InsertUser(ctx context.Context, arg InsertUserParams) error
	OfferJob(ctx context.Context, arg OfferJobParams) error
	PerformJobOfferAction(ctx context.Context, arg PerformJobOfferActionParams) error
	RegisterForJob(ctx context.Context, arg RegisterForJobParams) error
}

var _ Querier = (*Queries)(nil)
