// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	// and cgpa_cutoff <= (SELECT cgpa from student_table where student_id = $1);
	CreateJob(ctx context.Context, arg CreateJobParams) error
	GetEligibleStudents(ctx context.Context, jobID int32) ([]*StudentTable, error)
	// apply salary tier filter
	// apply job role filter
	// apply company filter
	// filter out companies whose application date expired.
	// filter out companies for which the student's branch is not eligible
	GetJobs(ctx context.Context, arg GetJobsParams) ([]*GetJobsRow, error)
	InsertUser(ctx context.Context, arg InsertUserParams) error
}

var _ Querier = (*Queries)(nil)
