// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetJobs(ctx context.Context, arg GetJobsParams) ([]*GetJobsRow, error)
}

var _ Querier = (*Queries)(nil)
