// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type User struct {
	ID             int32
	Name           string
	Branch         string
	Cgpa           string
	ActiveBacklogs int32
	EmailID        string
	Usn            string
	CounsellorName string
}
