// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (name, branch, cgpa, active_backlogs, email_id, usn, counsellor_name)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertUserParams struct {
	Name           string
	Branch         string
	Cgpa           float64
	ActiveBacklogs bool
	EmailID        string
	Usn            string
	CounsellorName string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.Name,
		arg.Branch,
		arg.Cgpa,
		arg.ActiveBacklogs,
		arg.EmailID,
		arg.Usn,
		arg.CounsellorName,
	)
	return err
}
